<?php

namespace DoctrineORMModule\Proxy\__CG__\Usuario\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class UsuarioListas extends \Usuario\Entity\UsuarioListas implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Usuario\\Entity\\UsuarioListas' . "\0" . 'idlistas', '' . "\0" . 'Usuario\\Entity\\UsuarioListas' . "\0" . 'titulo', '' . "\0" . 'Usuario\\Entity\\UsuarioListas' . "\0" . 'usuario', '' . "\0" . 'Usuario\\Entity\\UsuarioListas' . "\0" . 'listaTelefones', '' . "\0" . 'Usuario\\Entity\\UsuarioListas' . "\0" . 'validacao');
        }

        return array('__isInitialized__', '' . "\0" . 'Usuario\\Entity\\UsuarioListas' . "\0" . 'idlistas', '' . "\0" . 'Usuario\\Entity\\UsuarioListas' . "\0" . 'titulo', '' . "\0" . 'Usuario\\Entity\\UsuarioListas' . "\0" . 'usuario', '' . "\0" . 'Usuario\\Entity\\UsuarioListas' . "\0" . 'listaTelefones', '' . "\0" . 'Usuario\\Entity\\UsuarioListas' . "\0" . 'validacao');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (UsuarioListas $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdlistas()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdlistas();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdlistas', array());

        return parent::getIdlistas();
    }

    /**
     * {@inheritDoc}
     */
    public function getTitulo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitulo', array());

        return parent::getTitulo();
    }

    /**
     * {@inheritDoc}
     */
    public function getUsuario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuario', array());

        return parent::getUsuario();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdlistas($idlistas)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdlistas', array($idlistas));

        return parent::setIdlistas($idlistas);
    }

    /**
     * {@inheritDoc}
     */
    public function setTitulo($titulo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitulo', array($titulo));

        return parent::setTitulo($titulo);
    }

    /**
     * {@inheritDoc}
     */
    public function setUsuario($usuario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsuario', array($usuario));

        return parent::setUsuario($usuario);
    }

    /**
     * {@inheritDoc}
     */
    public function getListaTelefones()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getListaTelefones', array());

        return parent::getListaTelefones();
    }

    /**
     * {@inheritDoc}
     */
    public function setListaTelefones($listaTelefones)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setListaTelefones', array($listaTelefones));

        return parent::setListaTelefones($listaTelefones);
    }

    /**
     * {@inheritDoc}
     */
    public function getValidacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getValidacao', array());

        return parent::getValidacao();
    }

    /**
     * {@inheritDoc}
     */
    public function setValidacao($validacao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setValidacao', array($validacao));

        return parent::setValidacao($validacao);
    }

}
