<?php

namespace Produto\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FormatoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProdutoCampanhaRepository extends EntityRepository
{
}
