<div class="page-header">
  <h1>Minhas Listas<small> Nessa sessão você visualiza suas listas de forma completa e detalhada.</small></h1>
</div>

<table class="table table-condensed">
 	<tr>
 		<td><span class="label">ID</span></td>
 		<td><span class="label label-info">Titulo da lista</span></td>
 		<td><span class="label label-warning">Contatos</span></td>
 		<td><span class="label label-inverse">Ações</span></td>
 	</tr>
 	<tr class="info">
 		<td>01</td>
 		<td>Empresas em são paulo</td>
 		<td>10</td>
 		<td><button class="btn btn-mini btn-warning" type="button">Editar</button> <button class="btn btn-mini btn-danger" type="button">Excluir</button></td>
 	</tr>
</table>