<div class="page-header">
  <h1>Criação de listas<small> Crie suas listas para campanhas especificas ou público destinado.</small></h1>
</div>

<form>
	<input type="text" class="titulo" placeholder="Digite o título da sua lista"><br/>
	<textarea placeholder="Importe sua lista de telefones" style="width: 30%; height:200px;" class="listaConteudo"></textarea>
	<button class="btn btn-small btn-primary carregarLista" type="button">Carregar Lista</button>
	<button class="btn btn-small btn-danger salvarLista" type="button">Salvar Lista</button><br/>
	
	<span class="label label-info infoCarregados">N° Contatos carregado: 0</span>
</form>