<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Whatsapp Marketing'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
         <script>var basePatch  = '<?=$this->basePath()?>'</script>
        <?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
       									 ->prependFile($this->basePath() . '/js/jquery.maskedinput.min.js')
        								->prependFile($this->basePath() . '/js/bootstrap.file-input.js')
        							  ->prependFile($this->basePath() . '/js/sistema.js')
                                      ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                                      ->prependFile($this->basePath() . '/js/jquery.min.js') ?>

    </head>
    <body>
    <div id="popup-login">
	<span>
	 <img src="/siteBouts/www/img/load.gif">
	 <p>Carregando Aguarde...</p>
	</span>
</div>
    
    	<div id="geral">
			<div id="header">
				<div id="menu">
					<div class="btn-group">
					  <a href="<?=$this->url("enviarMensagem")?>"> <button class="btn"><i class="icon-map-marker"></i> Home</button></a>
					 <a href="<?=$this->url("sair")?>"> <button class="btn"><i class="icon-remove"></i> Sair</button></a>
					</div>
					<div id="infoPerfil">
						<span class="label">Olá <?
						if($this->infoUser)
						{
						print $this->infoUser->getLogin();
						}
						?> seja bem vindo</span> <span class="label label-info">N° Créditos: 20</span>
					</div>
				</div>
			</div>
			<div id="content">
				<div id="conteudo">
					<div id="menuLeft">
						<ul class="nav nav-list">
                <li class="nav-header"><i class="icon-star"></i>Pontos da Conta</li>
                <li <?if($this->setterMenu == "resulmoConta") print 'class="active"';?>><a href="<?=$this->url("resulmoConta")?>">Resulmo da Conta</a></li>
                <!--<li><a href="#">Transferência de pontos</a></li>
                <li><a href="#">Transações de pontos</a></li>  -->
                <li class="nav-header"><i class="icon-envelope"></i>Enviar Mensagens</li>
                <li <?if($this->setterMenu == "criarCampanha") print 'class="active"';?>><a href="<?=$this->url("criarCampanha")?>">Criar Campanhas</a></li>
                <li <?if($this->setterMenu == "enviarMensagem") print 'class="active"';?>><a href="<?=$this->url("enviarMensagem")?>">Mensagem Simples</a></li>
                <li <?if($this->setterMenu == "enviarCampanhas") print 'class="active"';?>><a href="<?=$this->url("enviarCampanhas")?>">Enviar Campanhas</a></li>
                 <li><a href="<?=$this->url("enviarCampanhas")?>">Gerenciar Campanhas</a></li>             
              	<li class="nav-header"><i class="icon-list"></i>Gerenciar Contatos</li>
              	<li <?if($this->setterMenu == "minhasListas") print 'class="active"';?>><a href="<?=$this->url("minhasListas")?>">Minhas Listas</a></li>
              	<li <?if($this->setterMenu == "criarLista") print 'class="active"';?>><a href="<?=$this->url("criarLista")?>">Criar Listas de contatos</a></li>
              	
              	<li class="nav-header"><i class="icon-user"></i>Conta do Perfil</li>
              	<li <?if($this->setterMenu == "verPerfil") print 'class="active"';?>><a href="<?=$this->url("verPerfil")?>">Ver Perfil</a></li>
              	<li <?if($this->setterMenu == "editarPerfil") print 'class="active"';?>><a href="<?=$this->url("editarPerfil")?>">Editar Perfil</a></li>
              </ul>
					</div>
					<div id="contentController">
						<div class="alert" style="display: none"></div>
						<?php echo $this->content; ?>
					</div>
				</div>
			</div>
		</div>	
        <div id="footer">
				<div id="menu_footer">
					<ul class="mn_footer">
						<li>WHATSAPP COPYRIGHT © 2014</li>
						<li>TODOS OS DIREITOS RESERVADOS</li>
					</ul>
				</div>

			    </div>
    </body>
</html>
