<div class="page-header">
  <h1>Criar Campanhas  <small>Crie Campanhas para seu público específico.</small></h1>
</div>

<div class="alert alert-info">
  <button type="button" class="close" data-dismiss="alert">&times;</button>
  <strong>Atenção!</strong> Após criada sua campanha, acesse o menu enviar campanhas para um melhor acompanhamento de seus envios.
</div>   
<form>
  <fieldset>
    <input type="text" placeholder="Digite o título da campanha" style="margin-top:10px;">
    <select style="margin-top:10px;">
    	<option>Selecione a lista de contatos</option>
    </select> <input type="file" title="Adicionar Imagem " class="btn btn-danger"><br/>
    <textarea style="width:90%;height:200px;" placeholder="Digite a mensagem que será enviada para seu contato."></textarea><br/>
    <button type="submit" class="btn btn-primary">Criar Campanha</button>
  </fieldset>
</form>           