<div class="page-header">
  <h1>Enviar Campanhas  <small>Envie suas campanhas e tenha e controle de seus envios nessa sessão.</small></h1>
</div>
<table class="table table-condensed">
 	<tr>
 		<td><span class="label">ID</span></td>
 		<td><span class="label label-info">Titulo da Campanha</span></td>
 		<td><span class="label label-warning">Situação</span></td>
 		<td><span class="label label-inverse">Ações</span></td>
 	</tr>
 	<tr class="warning">
 		<td>01</td>
 		<td>Campanha para copa do mundo</td>
 		<td>01/1000</td>
 		<td> <button class="btn btn-mini btn-danger" type="button">Excluir</button></td>
 	</tr>
 	<tr class="info">
 		<td>01</td>
 		<td>Campanha de páscoa</td>
 		<td>01/1000</td>
 		<td> <button class="btn btn-mini btn-primary" type="button">Enviar</button> <button class="btn btn-mini btn-warning" type="button">Editar</button></td>
 	</tr>
</table>