<div class="page-header">
  <h1>Enviar Mensagem  <small>Envie mensagens de testes, ou para um cliente especifico.</small></h1>
</div>

<form>
  <fieldset>
    <input type="text" placeholder="Telefone ex:5511999998888" style="margin-top:10px;">
    <input type="file" title="Adicionar Imagem " class="btn btn-danger"><br/>
    <textarea style="width:90%;height:200px;" placeholder="Digite a mensagem que será enviado para os contatos de sua campanha."></textarea><br/>
    <button type="submit" class="btn btn-primary">Enviar Mensagem</button>
  </fieldset>
</form> 