<div class="page-header">
  <h1>Enviar Campanhas  <small>Envie suas campanhas e tenha e controle de seus envios nessa sessão.</small></h1>
</div>
<div class="alert">
  <strong>Atenção:</strong> Veja abaixo a legenda de situações existe para seus envios.<br/>
  - Aguardando confirmação, Sistema aguada seu envio.<br/>
  - Cancelado, Foi cancelado seu envio.<br/>
  - Enviando, O sistema está enviando suas mensagens.<br/>
  - Concluído, Sistema envio com sucesso todas suas mensagens.
</div>
<table class="table table-condensed">
 	<tr>
 		<td><span class="label">ID</span></td>
 		<td><span class="label label-info">Titulo da Campanha</span></td>
 		<td><center><span class="label label-warning">Situação</span></center></td>
 		<td><span class="label label-inverse">Ações</span></td>
 	</tr>
 	<!-- 
 	<tr class="warning">
 		<td>01</td>
 		<td>Campanha para copa do mundo</td>
 		<td>01/1000</td>
 		<td> <button class="btn btn-mini btn-danger" type="button">Excluir</button></td>
 	</tr> -->
 	<?php 
 		foreach($this->data AS $data)
 		{
 	?>
 	<tr class="info table<?=$data->getIdcampanha()?>">
 		<td><?=$data->getIdcampanha()?></td>
 		<td><?=$data->getTitulo()?></td>
 		<td><center>Aguardando confirmação</center></td>
 		<td> <button class="btn btn-mini btn-primary enviarCampanha" type="button" rel="<?=$data->getIdcampanha()?>">Enviar</button> <button class="btn btn-mini btn-warning" type="button">Editar</button> <button class="btn btn-mini btn-danger" type="button">Excluir</button></td>
 	</tr>
 	<?php 
 		}
 	?>
</table>
<?php 
	if(!$this->data)
	{
		?>
		<div class="alert">
  <button type="button" class="close" data-dismiss="alert">&times;</button>
  <strong>Atenção!</strong> Não existe novas campanhas, para cadastrar acesse: <a href="<?=$this->url("criarCampanha")?>">Criar Campanhas.</a>
</div>
		<?php 
	}
?>